# Pages placed under these sections will be shown on homepage and archive page.
mainSections = ["post"]
# Output page's full content in RSS.
rssFullContent = true

[footer]
since = 2023
customText = ""

[dateFormat]
published = "Jan 02, 2006"
lastUpdated = "Jan 02, 2006 15:04 MST"

[sidebar]
emoji = ""
subtitle = "Urbanism, transit, and programming – what could go wrong?"

[sidebar.avatar]
enabled = true
local = false
src = "https://lh3.googleusercontent.com/qW2jNAEvyx_59Si8xHBU2KdLf6obRG9d3XuJoX2eEM5nt8py9S6dZlPlLmm33WQAiu3OVi_xcJrsyJXGPdA7CSGY--VDF76_2-8ADxykWE0DMPw1Ox0Hj_mGDBtbAsRp4vwbJ7Skqu5bMTZNHWUnbCEB2anuAl7DnZUQfuGPC2WAr_gv58w9PlchnwwfIRmdd97BLrnw5hr7_Osh85oC4s3DGQ0knBJT4joizU_dPh6ztp-Y9wNWHnAQJHXdrozFezoHob7li4MQ8gLXDLG5Dc00fwzbgVGIN5OoNe-0iSiJ8jIzqvAWv1F6eaoN6o8lkI_5AkEuyw3de0VrrSX1luHed-clCGTS1Y1wiFdoQ-jMA2XbQNU0f-5ITEHlYQXPJLvpXAXYwEWaX6y7VTgsZ76w3HH7kTtgZz8KQFvo6U6d4AT1lzhEWzPDsT9l5nq2CPCJKhshQw041WIsunbS_EBKaUF0pNDgq9y7YnsHGQ3M7_CGONEM5D8F3Oes8YNH43qXRSp68uRXTYzbC34blciiHliaL_f47XW8Ed1esh3sdfnksxyroTX_-topL_nU0MMUcqCjaL0JtIOtU4rEdJKQov2WJKw3AnT8EFmEhPPq7d59FmmuGxU41vFbQ-yntWxLPFkAtXHPib3X-FA_xNd2YW3uO6kign_vZAt_sjLMjOMYRgn8_qIxZ8DoXFnELCcw0omHJ8TDCM8GpEh9I2a-jpZBT9S19A0-03RYOObCHFT5kxnN9Nz_lQFBj4BFOHQ2iKVMJspGvmyoTZeRhUyiG5TiZXzthMsWpKoOLKiwCFVfv6AxF_bhcfLWL4UcjUMFPRCbgZ35LWOKUi0mqdciAvowp82lWSGhHfVS6oHuk-_yYz0kBuwBeyaPlnUSVG2nzW1Jylz2bmOBOfk6WywZlg0pYVxsvqs0EMzDUe-xmadIYQ=w2708-h2030-no?authuser=0"

[article]
math = false
readingTime = true

[article.license]
enabled = false
default = "Licensed under CC BY-NC-SA 4.0"

## Widgets
[[widgets.homepage]]
type = "search"

[[widgets.homepage]]
type = "archives"

[widgets.homepage.params]
limit = 5

[[widgets.homepage]]
type = "categories"

[widgets.homepage.params]
limit = 10

[[widgets.homepage]]
type = "tag-cloud"

[widgets.homepage.params]
limit = 10

[[widgets.page]]
type = "toc"

[opengraph.twitter]
site = ""
card = "summary_large_image"

[defaultImage.opengraph]
enabled = false
local = false
src = ""

[colorScheme]
toggle = true
default = "auto"

[imageProcessing.cover]
enabled = true

[imageProcessing.content]
enabled = true

## Comments
[comments]
enabled = false
provider = "disqus"

[comments.disqusjs]
shortname = ""
apiUrl = ""
apiKey = ""
admin = ""
adminLabel = ""

[comments.utterances]
repo = ""
issueTerm = "pathname"
label = ""

[comments.remark42]
host = ""
site = ""
locale = ""

[comments.vssue]
platform = ""
owner = ""
repo = ""
clientId = ""
clientSecret = ""
autoCreateIssue = false

[comments.waline]
serverURL = ""
lang = ""
visitor = ""
avatar = ""
emoji = ["https://cdn.jsdelivr.net/gh/walinejs/emojis/weibo"]
requiredMeta = ["name", "email", "url"]
placeholder = ""

[comments.waline.locale]
admin = "Admin"

[comments.twikoo]
envId = ""
region = ""
path = ""
lang = ""

[comments.cactus]
defaultHomeserverUrl = "https://matrix.cactus.chat:8448"
serverName = "cactus.chat"
siteName = ""

[comments.giscus]
repo = ""
repoID = ""
category = ""
categoryID = ""
mapping = ""
lightTheme = ""
darkTheme = ""
reactionsEnabled = 1
emitMetadata = 0

[comments.gitalk]
owner = ""
admin = ""
repo = ""
clientID = ""
clientSecret = ""

[comments.cusdis]
host = ""
id = ""
